"""Shared Pydantic v2 models for REST, signaling, ASR and subtitles.

Example:
    from ru_tat_call_shared.contracts import LoginRequest, parse_signaling_message
"""

from ru_tat_call_shared.contracts.asr import (
    AsrAudioPayload,
    AsrErrorPayload,
    AsrFinalEvent,
    AsrInfoPayload,
    AsrMessage,
    AsrPartialEvent,
    AsrStartPayload,
    AsrStopPayload,
    AsrTranscriptPayload,
    parse_asr_message,
)
from ru_tat_call_shared.contracts.common import (
    ApiModel,
    ErrorCode,
    ErrorPayload,
    LanguageMode,
    SpeechLanguage,
    SubtitleStatus,
)
from ru_tat_call_shared.contracts.rest import (
    AddContactRequest,
    AddGroupMemberRequest,
    ContactItem,
    ContactsListResponse,
    CreateGroupRequest,
    GroupItem,
    GroupsListResponse,
    LoginRequest,
    LoginResponse,
    TranscriptionSettings,
    TranscriptSegment,
    TranscriptResponse,
    UserProfile,
)
from ru_tat_call_shared.contracts.signaling import (
    CallAcceptPayload,
    CallInvitePayload,
    CallRejectPayload,
    IceCandidate,
    ParticipantPayload,
    RoomCreatePayload,
    RoomCreatedPayload,
    SignalingErrorEvent,
    SignalingMessage,
    WebrtcAnswerPayload,
    WebrtcIcePayload,
    WebrtcOfferPayload,
    parse_signaling_message,
)
from ru_tat_call_shared.contracts.subtitles import SubtitleUpdateEvent, SubtitleUpdatePayload

__all__ = [
    "ApiModel",
    "ErrorCode",
    "ErrorPayload",
    "LanguageMode",
    "SpeechLanguage",
    "SubtitleStatus",
    "AddContactRequest",
    "AddGroupMemberRequest",
    "ContactItem",
    "ContactsListResponse",
    "CreateGroupRequest",
    "GroupItem",
    "GroupsListResponse",
    "LoginRequest",
    "LoginResponse",
    "TranscriptionSettings",
    "TranscriptSegment",
    "TranscriptResponse",
    "UserProfile",
    "CallAcceptPayload",
    "CallInvitePayload",
    "CallRejectPayload",
    "IceCandidate",
    "ParticipantPayload",
    "RoomCreatePayload",
    "RoomCreatedPayload",
    "SignalingErrorEvent",
    "SignalingMessage",
    "WebrtcAnswerPayload",
    "WebrtcIcePayload",
    "WebrtcOfferPayload",
    "parse_signaling_message",
    "AsrAudioPayload",
    "AsrErrorPayload",
    "AsrFinalEvent",
    "AsrInfoPayload",
    "AsrMessage",
    "AsrPartialEvent",
    "AsrStartPayload",
    "AsrStopPayload",
    "AsrTranscriptPayload",
    "parse_asr_message",
    "SubtitleUpdateEvent",
    "SubtitleUpdatePayload",
]
